#!/bin/bash

SELF_IP="127.0.0.1"
LISTEN_IP="0.0.0.0"
MIN_NODES_SIZE="${MIN_NODES_SIZE:-3}"
SSL_AUTH="${SSL_AUTH:-"no"}"
SSL_CA=""
SSL_CERT=""
SSL_KEY=""
if [[ "$SSL_AUTH" == "yes" ]]; then
  export SSL_AUTH
fi
if [[ -n "$SERVICE_NAME" ]]; then
  echo "service name given: $SERVICE_NAME - we are running in swarm mode"
  # wait for all nodes to appear
  number_of_nodes=1
  while [[ $number_of_nodes -lt ${MIN_NODES_SIZE} ]]; do
    sleep 1
    SELF_IP=$(dig +short $(hostname))
    NODES=$(dig +short tasks.${SERVICE_NAME})
    number_of_nodes=$(( $(echo $NODES | grep -o '\s' | wc -l) + 1 )) >/dev/null
    echo "we found $number_of_nodes nodes"
  done
  echo "self ip: $SELF_IP"
  echo "peer nodes: $NODES"
fi
export SELF_IP
export LISTEN_IP
render.py /etc/vernemq/vernemq.conf.j2 > /etc/vernemq/vernemq.conf
/usr/share/vernemq/bin/vernemq config generate | grep error
if [ $? -ne 1 ]; then
    echo "configuration error, exit"
    echo "$(cat /usr/share/vernemq/bin/../etc/vernemq.conf)"
    exit 1
fi
echo running /usr/share/vernemq/bin/vernemq start
/usr/share/vernemq/bin/vernemq start
output=""
echo -n "waiting for node to finish booting"
while [[ "$output" != "pong" ]]; do
  echo -n "."
  sleep 0.1
  output=$(/usr/share/vernemq/bin/vernemq ping)
done
echo "done"
tail -F /var/log/vernemq/* &
/usr/share/vernemq/bin/vernemq getpid  > /var/run/vernemq.pid

for node in ${NODES}; do
  echo "trying to join node $node"
  /usr/share/vernemq/bin/vmq-admin cluster join discovery-node=VerneMQ@$node
done

echo "config:"
cat /etc/vernemq/vernemq.conf | while read line; do echo -e "\t$line"; done
fork_proxy.sh /var/run/vernemq.pid "echo started"
