#!/bin/bash

SELF_IP="127.0.0.1"
if [[ -n "$SERVICE_NAME" ]]; then
  SELF_IP=$(dig +short $(hostname))
  NODES=$(dig +short tasks.${SERVICE_NAME})
fi
export SELF_IP
render.py /etc/vernemq/vernemq.conf.j2 > /etc/vernemq/vernemq.conf
/usr/share/vernemq/bin/vernemq config generate | grep error
if [ $? -ne 1 ]; then
    echo "configuration error, exit"
    echo "$(cat /usr/share/vernemq/bin/../etc/vernemq.conf)"
    exit 1
fi
echo running exec /usr/share/vernemq/bin/vernemq start
/usr/share/vernemq/bin/vernemq start
ps aux | grep '[b]eam.smp' | awk '{print $2}' > /var/run/vernemq.pid
for node in ${NODES}; do
  echo "trying to join node $node"
  vmq-admin cluster join discovery-node=$node
done
fork_proxy.sh /var/run/vernemq.pid
